[resolve #18] Add C++ allocator (partial)
spcl/rFaaS pull request #28
Opened 2023-04-02 20:31 UTC by William-Mou

## Story

This PR is open for issue #18, including the following features.

  - [x]  Add allocator implementation in rfaaslib.
  - [x] Encapsulate the memory registration in rdmalib 
    - [ ] provide generic enums for local/remote read/write ops + atomics.
  - [x] Support in allocator registration 
    - [ ] and deregistration of memory. (not test yet)
  - [x] Add test demonstrating standard memory allocation.
  - [ ] Add test demonstrating allocation with std::vector and our custom allocator.

## Achievements

- Defines `rdma_allocator.hpp`, which provides the allocate and deallocate functions.
- Use `rfaas::RdmaAllocator<rdmalib::Buffer<char> > rdmaAllocator(executor);` to instantiate the allocator object.
- `rdmaAllocator.allocate(size_t size, int access)` intuitively allocates memory space for a buffer.

## Test
- By embedding `std::cout` in the allocator, you can test the program to run as expected.
![](https://i.imgur.com/yeUw13R.png)

## TODO
- Complete the tasks not checked above

2023-04-03 10:38 UTC, mcopik requested changes

2023-04-03 10:38 UTC, mcopik commented on rfaas/include/rfaas/rdma_allocator.hpp
> +  template<typename T>
I think the allocator should be of type `T`, and then always return `rdmalib::Buffer` object. If you look at the [C++ allocator concept](https://en.cppreference.com/w/cpp/named_req/Allocator), then I think we should use `A::pointer` as `rdmalib::Buffer`.

2023-04-03 10:38 UTC, mcopik commented on rfaas/include/rfaas/rdma_allocator.hpp
> +      auto buffer = new rdmalib::Buffer<char>(size, header);
I don't think we need dynamic allocation for the buffer object itself :-) Once we properly define the pointer type.

2023-04-03 15:38 UTC, William-Mou commented
Hi @mcopik, 
I have updated my code to have a structure similar to the documentation, which may help with communication 😊

2023-04-03 22:13 UTC, mcopik commented
@William-Mou Thanks! I will try to test this and merge in the coming days :)

2023-04-11 16:12 UTC, William-Mou commented
I proposed a better solution in #30, so #28 has been closed.

2023-04-11 16:12 UTC, closed without merging